### ISSUE TITLE
bug calendar

### ISSUE THREAD

**Issue by plalanne** [ThomasPrioul/mdl-angular-libs#18]
Yep
je viens de voir un problème avec le calendar double.
quand tu clques sur le petit agenda pour le faire apparaitre il y a une message d'erreur dans la console

![image](https://github.com/ThomasPrioul/mdl-angular-libs/assets/7156531/a391efdd-c685-44f0-a32d-386b5f1bd0d9)

**Comment by ThomasPrioul** [comment]
Salut, il n'y a pas ce bug sur le showcase j'ai l'impression.
On dirait une boucle infinie, tu es dans un composant avec le mode OnPush ou pas (le showcase est en OnPush) ?
Je vais MAJ le showcase déployé déjà et après je regarderai pour reproduire ton bug

**Comment by plalanne** [comment]
bion si justement il est aussi sur le showcase, j'ai vérifié avant de te remonter le bug pour etre sur que ca ne vienne pas de ce que j'ai fait

**Comment by ThomasPrioul** [comment]
Bon je n'ai pas pu reproduire le bug mais d'après le message que tu as partagé au tout début, j'ai ajouté un bout de code qui pourrait éviter la boucle infinie, peux-tu tester le showcase depuis la branche `bug/calendar-infinite-loop` et me dire si c'est bon ?

**Comment by ThomasPrioul** [comment]
Sur le commit 9a1c1f749830416a91fe5b624465ce223b542722 ?
Moi je ne l'ai plus...
