### ISSUE TITLE
Pouvoir avoir la position de la pagination en option

### ISSUE THREAD

**Issue by plalanne** [ThomasPrioul/mdl-angular-libs#26]
positionner la pagination comme on le veut (haut/bas, droite/gauche)

**Comment by ThomasPrioul** [comment]
Quand le paginator est en haut, comment on gère par rapport au header ?
On le force en dessous?
On le met à côté du header et on réduit la search bar ?

**Comment by ThomasPrioul** [comment]
Il y a la notion de "paginatorAddons", c'est un ng-template où tu mets ce que tu veux dedans à côté du paginator.
Tu peux choisir le côté des addons, ce qui indirectement choisit le côté du paginator. ça marche même si tu n'utilises pas le slot pour ton contenu.
![image](https://github.com/ThomasPrioul/mdl-angular-libs/assets/15314924/a646ae06-aaa0-4480-9fbd-0d6dc9948dec)
Dispo dans la v0.0.24
