### ISSUE TITLE
mdl-table2 input non clair

### ISSUE THREAD

**Issue by plalanne** [ThomasPrioul/mdl-angular-libs#5]
[disableSearch]="false"
[toolbar]="true"

on ne voit pas le search il est dépendant de la toolbar

**Comment by ThomasPrioul** [comment]
![image](https://github.com/ThomasPrioul/mdl-angular-libs/assets/15314924/665c2058-afd0-41a5-ab08-774e6d1162fd)
Corrigé dans v0.0.8
