### ISSUE TITLE
font family "Material Icons" au lieu de "Material icons Outlined" pour faire apparaitre les icons dans la snackbar

### ISSUE THREAD

**Issue by plalanne** [ThomasPrioul/mdl-angular-libs#54]
voir le titre

**Comment by ThomasPrioul** [comment]
Le SCSS cherche une font manquante "Material icons Outlined".
Material crée automatiquement le css de la font family "Material Icons", à utiliser en lieu et place.
Faire apparaitre la snackbar dans l'appli showcase pour ne plus avoir de pb
