### ISSUE TITLE
table2: pouvoir changer l'offset de pagination lorsque l'on est en plein écran

### ISSUE THREAD

**Issue by Xavilanc** [ThomasPrioul/mdl-angular-libs#57]
Actuellement, le select qui permet de changer le nombre d'élément par page est inactif lorsque l'on est en plein écran.
Le but serait d'ajouter la possibilité de changer le nombre d'élément par page lorsque l'utilisateur est en mode plein écran.

**Comment by ThomasPrioul** [comment]
Bug non présent dans la demo qui utilise la release v0.0.32
Il faut utiliser le provider suivant `{ provide: OverlayContainer, useClass: FullscreenOverlayContainer }` dans le app.module ou autre module qui importe les dépendances d'Angular Material

**Comment by Xavilanc** [comment]
C'est bon ça fonctionne, merci bien.
