### ISSUE TITLE
filter on select

### ISSUE THREAD

**Issue by plalanne** [ThomasPrioul/mdl-angular-libs#7]
Actuellement sur les select le filtre ne semble fonctionner que si [value] renvoie une valeur de type string
Dans quasiment tous mes select je renvoie un objet et donc le tri ne fonctionne pas

Il faudrait soit pouvoir injecter la fonction de tri souhaitée ou alors alors rendre le tri possible sur les objets. Je ne sais pas si c'est faisable mais en l'etat je ne peux pas utiliser le mat-select

**Comment by ThomasPrioul** [comment]
Je ne comprends pas la question, tu parles de filtre puis de tri ?
Le composant mdl-select-filter est juste une input donc forcément la valeur tapée est une string. C'est de la responsabilité de l'application de gérer les items à supprimer du *ngFor en fonction du filtre en string ce n'est pas la lib qui gère.
C'est aussi de la responsabilité de l'application de trier les items (dans le ngFor aussi).
Voici un exemple :
https://github.com/ThomasPrioul/mdl-angular-libs/blob/f7001475d82aa46a0042941f04c0818ecf41f878/projects/showcase/src/pipes/series-filter.pipe.ts

```ts
import { Pipe, PipeTransform } from '@angular/core';
import { Serie } from '../models/serie';


@Pipe({
  name: 'seriesFilter',
  standalone: true,
  pure: true,
})
export class SeriesFilterPipe implements PipeTransform {
  public transform(serie: Serie, filter?: string) {
    const filterLow = filter?.toLocaleLowerCase();
    return this.filterSerie(serie, filterLow);
  }


  private filterSerie(serie: Serie, filter?: string) {
    return (
      !filter ||
      serie.codeLcn.toLocaleLowerCase() === filter ||
      serie.codeSerieMateriel.toLocaleLowerCase().includes(filter) ||
      serie.nomTechniqueComplet.toLocaleLowerCase().includes(filter)
    );
  }
}
```

**Comment by plalanne** [comment]
Alors ok c'est pas tri mais filtre, désolé.
Et apres j'avais pas compris comment tu avais filtré, j'ai mal examiné le code et j'avais pas vu le SeriesFilterPipe. Donc a priori ce ticket n'a plus lieu d'etre
My bad. Je teste ca demain

**Comment by plalanne** [comment]
Bon c'est bon ca fonctionne !!! c'est moi qui ait mal analysé ton code de démo !! je suis un boulet !!! Bonnes vacances
