### ISSUE TITLE
Ajouter la possibilité d'avaoir un selectAll/ClearAll sur les select

### ISSUE THREAD

**Issue by plalanne** [ThomasPrioul/mdl-angular-libs#8]
![image](https://github.com/ThomasPrioul/mdl-angular-libs/assets/7156531/1a6b953b-3717-497c-ac88-37be7a329c88)

**Comment by ThomasPrioul** [comment]
Dac, en attendant l'implémentation tu peux toi même l'ajouter dans le select, surtout si tu as un formControl il suffit de faire un reset(), pour le selectAll c'est facile aussi

**Comment by ThomasPrioul** [comment]
@plalanne Je suis en train de l'implémenter, qu'en penses-tu ?
![image](https://github.com/ThomasPrioul/mdl-angular-libs/assets/15314924/f7a9342e-9d20-4730-895b-4aa8a3f8777e)
![image](https://github.com/ThomasPrioul/mdl-angular-libs/assets/15314924/d8f587f1-a3fd-426b-b608-dbce03bee811)

Niveau code ce n'est qu'un attribut en + : ![image](https://github.com/ThomasPrioul/mdl-angular-libs/assets/15314924/fa969b15-8fae-46bf-843d-3e0945096c41)

Le bouton est focusable avec la flèche gauche depuis l'input de recherche

**Comment by ThomasPrioul** [comment]
Testable dans la version 0.0.9 : https://github.com/ThomasPrioul/mdl-angular-libs/releases/tag/v0.0.9

**Comment by plalanne** [comment]
C'est bon pour moi !! thanks

**Comment by ThomasPrioul** [comment]
Implémenté dans la release v0.0.9
